# -*- coding: utf-8 -*-
"""DSCI330_act1.4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iqaSeb-FvZbQzTJ6fZzv751r9JMFs0qt
"""

# 1.1
triangle_area = lambda b, h: 0.5*b*h

triangle_area(1,2)

# 1.3
# Test function
def test_triangle_area():
    assert triangle_area(1,2) == 1
    assert triangle_area(3,4) == 6
    assert triangle_area(5,6) == 15
test_triangle_area() # Silence is golden!

# 1.4
def triangle_area():
    """ compute the area of a right triangle with base b and height h """
    output = 0.5*b*h
    return output

# 1.5
def new_triangle_area(b, h):
    """ compute the area of a right triangle with base b and height h """
    output = 0.5*b*h
    return output

# 1.6 a
# Test function
def test_new_triangle_area():
    assert triangle_area(1,2) == 1
    assert triangle_area(3,4) == 6
    assert triangle_area(5,6) == 15
test_triangle_area() # Silence is golden!

# 1.6 b
help(new_triangle_area)

